---
- hosts: all
  become: true
  tasks:
    - name: Install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker on Ubuntu
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start Docker
      service:
        name: docker
        state: restarted

